FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    apache2 \
    apt-utils \
    libapache2-mod-php7.2 \
    php-curl \
    php-gd \
    php-intl \
    php-mbstring \
    php-mysql \
    php-soap \
    php-xdebug \
    php-xml \
    php-xmlrpc \
    php-zip \
    unzip \
    zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir /var/moodledata

COPY docker/config/apache-site.conf /etc/apache2/sites-available/apache-site.conf
COPY docker/config/xdebug.ini /etc/php/7.2/mods-available/xdebug.ini

RUN chown -R www-data:www-data /var/www/html \
    && chown -R www-data:www-data /var/moodledata \
    && a2enmod rewrite \
    && a2dissite 000-default \
    && a2ensite apache-site.conf

CMD apachectl -D FOREGROUND
